Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Warning: NAs introduced by coercion 

Error in plot.new() : figure margins too large 
Traceback: 
[1] "3: plot.new()"                                                            
[2] "2: plot.default(log10(gage_values), type = \"l\", main = paste(\"Gage\", "
[3] "       gage), xlab = \"timestep\", ylab = \"discharge\")"                 
[4] "1: plot(log10(gage_values), type = \"l\", main = paste(\"Gage\", gage), " 
[5] "       xlab = \"timestep\", ylab = \"discharge\")"                        

